### ISSUE TITLE
2.5.0 performance bottleneck above 10240B?

### ISSUE THREAD

**Issue by ghost** [gwhalin/Memcached-Java-Client#3]
I’ve been running the numbers to compare 2.0.1 and 2.5.0 and I’ve noticed something. This is against a simple single thread unit test with 64B, 1024B, 10240B, and 102400B. The first 3 perform as I would expect but at 102400b, it goes to crap. Not sure where the actual threshold is but above 10240B, each additional 10240B adds about an additional 2-3 seconds to the test.

With client 2.0.1
testCaching64B
###### ## Total time: 2813

testCaching1024B
###### ## Total time: 2958

testCaching10240B
###### ## Total time: 4473

testCaching102400B
###### ## Total time: 6835

Now with client 2.5.0 (same server):
testCaching64B
###### ## Total time: 2420

testCaching1024B
###### ## Total time: 2637

testCaching10240B
###### ## Total time: 3551

testCaching102400B
###### ## Total time: 20977

(This was on an 8 way, linux, 64bit box with 16gb ram)

Are others seeing this? Do you have any idea what might cause this? Based on these numbers, we won’t be able to upgrade.

**Comment by newroot** [comment]
Hi, hubbardr1,

Thanks very much for trying our new version of memcached client.
By default, the threshold is 1Mb in our design; due to our test, it's good in proceeding 100kb or even 1mb value.
Could you please give us your snippets of testing code so that I can reproduce this issue? And also you can check out the source code(branch of performance) and debug the issue by yourself, we will be very appreciated if you can help verify this problem.

And which is the version of memcached server?

Thanks again for giving us the first issue of this new version.

**Comment by newroot** [comment]
We tested it carefully in other ways, and didn't find this bug yet.
