### ISSUE TITLE
Deploy Memcached-Java-Client to maven central

### ISSUE THREAD

**Issue by PiouseLeo** [gwhalin/Memcached-Java-Client#42]
Could you please deploy Memcached-Java-Client-xxx.jar to maven central, in order that developers using maven get more convenience.

thx

**Comment by newroot** [comment]
Good suggestion. Thanks.

**Comment by newroot** [comment]
You can now found memcached java client on sonatype release.
it's version is 3.0.0, but we changed the namespace according the upload policy since danga.com is not under our control.

Now the namespace is whalin.com, nothing else is changed.

it will sync to maven central in a couple of days, please try.

Simple search "com.whalin" or "Memcached-Java-Client"

**Comment by PiouseLeo** [comment]
Thanks a lot.
