### ISSUE TITLE
the bin.jar and source.jar mismatch

### ISSUE THREAD

**Issue by phoenix** [gwhalin/Memcached-Java-Client#46]
I can't debug Memcached-Java-Client with the source.jar,because I can't set breakpoint in my IDE,the code line in class and source is not the same?

**Comment by giridharkannan** [comment]
While compiling form source they would have missed to include -g that's the reason for miss leading code line. If needed compile the source with -g and use it.

**Comment by newroot** [comment]
It should be same, if it is not, please checkout from github.

---

Xingen Wang

------------------ Original ------------------
From:  "phoenix"reply@reply.github.com;
Date:  Fri, Aug 3, 2012 04:53 PM
To:  "Xingen Wang"new.root@gmail.com; 

Subject:  [Memcached-Java-Client] the bin.jar and source.jar mismatch (#46)

I can't debug Memcached-Java-Client with the source.jar,because I can't set breakpoint in my IDE,the code line in class and source is not the same?

---

Reply to this email directly or view it on GitHub:
https://github.com/gwhalin/Memcached-Java-Client/issues/46
