### ISSUE TITLE
bug on set over 1M data

### ISSUE THREAD

**Issue by momentwdj** [gwhalin/Memcached-Java-Client#56]
I want to set over 1M data. But set function always return False.
download source code to find the answer.
I find the bug on AscIIClient.java near line 409.
setp1:set cmd
setp2:set data
setp3:set length
If data over 1M on setp2 the buffer will be full it will flush the bytes into the socket.It naver going to setp3.
I fix it but I don't know hao to share it.

Help me.
Thinks

**Comment by momentwdj** [comment]
digin@digin-wu:/tmp$ diff a b
21a22

> ```
>           output.write(b);//error on here
> ```
> 
> 23,30d23
> <               byte[] objectSize = new Integer(valLen).toString().getBytes();
> <               int oldPosition = sock.writeBuf.position();
> <               sock.writeBuf.position(offset);
> <               // put real object bytes size
> <               sock.writeBuf.put(objectSize);
> <               // return to correct position.
> <               sock.writeBuf.position(oldPosition);
> <               output.write(b);
> 37,43d29
> <               byte[] objectSize = new Integer(valLen).toString().getBytes();
> <               int oldPosition = sock.writeBuf.position();
> <               sock.writeBuf.position(offset);
> <               // put real object bytes size
> <               sock.writeBuf.put(objectSize);
> <               // return to correct position.
> <               sock.writeBuf.position(oldPosition);
> 47c33,39
> 
> ## <           
> 
> ```
>       byte[] objectSize = new Integer(valLen).toString().getBytes();
>       int oldPosition = sock.writeBuf.position();
>       sock.writeBuf.position(offset);
>       // put real object bytes size
>       sock.writeBuf.put(objectSize);
>       // return to correct position.
>       sock.writeBuf.position(oldPosition);
> ```

**Comment by newroot** [comment]
- please make sure memcached server support >1M, for memcached 1.4+, use -I <size>Override the default size of each slab page. Default is 1mb. Default is 1m, minimum is 1k, max is 128m. Adjusting this value changes the item size limit. Beware that this also increases the number of slabs (use -v to view), and the overal memory usage of memcached.
- in client side, within io pool, use 
  /**
  - In memcached 1.4+, user can specify memory size for each memcached item.<br>
  - You can specify it with parameter "-I" in the server side.<br>
  - While in our client side, we make the max memcached item size with the
  - default value 1Mb.<br>
  - In this scenario, you can extend the size as what you want, please be
  - sure you have enough memory in the client side, since we are using direct
  - buffer to hold the memory, they will not be free until shutdown.
  - 
  - @param bufferSize
  -            specified buffer size.
    */
    public void setBufferSize(int bufferSize) {
    schoonerSockIOPool.setBufferSize(bufferSize);
    } 
    ------------------
    Xingen Wang

------------------ Original ------------------

**Comment by momentwdj** [comment]
Thinks a lot.
I try setBufferSize it's useful for me.
