### ISSUE TITLE
cas unique data type?

### ISSUE THREAD

**Issue by ghost** [gwhalin/Memcached-Java-Client#6]
This is not really an issue but a question instead.  It's said in memcached protocol that "cas unique" is a 64 bit integer.  I have two questions regarding this:
1. I assume that it's a signed integer.  So it's value could be negative?
2. Is 0 the "cas unique" returned for non existing entries?

Thanks.

**Comment by mengli** [comment]
Hi noisebar,

Thanks very much for trying our new version of memcached client.

As to your first question, I have the following answers:
1) "cas" is a check and set operation which means "store this data but only if no one else has updated since I last fetched it.
This operation is implemented by checking the value of "cas unique".
2) "cas unique" is a unique 64-bit value generated by the memcached server. I can be negative if you assume it is signed integer.
But what we care about is whether it is equal the original one.

As to your second question, I have the following answers:
1) The memcached server will just return nothing followed by "END\r\n" for a non existing entry.

**Comment by ghost** [comment]
Thanks for the reply.  I guess my main concern with question 1 is that if the server uses unsigned 64 bit integer, it could potentially overflow Java long type.  But as far as I can tell from the protocol, it's signed.  As for question 2, I'd like to confirm what will be in MemcachedItem returned from gets() method.

Thanks.

BTW, awesome work on the performance improvement.

**Comment by mengli** [comment]
1) Cas unique won't overflow Java long type.
2) If the you "gets" a non existing entry, the "value" field of MemcachedItem will be set to null and "casUnique" field will be 0.
